#!/bin/sh                                                                                          
dir=$(pwd)                                                                                            
server=192.241.198.85                                                                                 
user=root
if [ "$1" = "ssh" ]
then
  command="ssh $user@$server"
else
  subcommand=$user@$server:$dir/$1                                                                   
  command="scp $1 $subcommand"
fi
echo $command                                                                                      
$command   
