# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=20000
SAVEHIST=20000
bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/Users/ankitmittal/.zshrc'

# autoload -Uz compinit
# compinit
# End of lines added by compinstall


#copying for autojump utility
[[ -s $(brew --prefix)/etc/profile.d/autojump.sh ]] && . $(brew --prefix)/etc/profile.d/autojump.sh

#setting up aliases
source ./alias
source ./funcs
source /Users/ankitmittal/repos/sandbox/zsh/zsh-git-prompt/zshrc.sh
PROMPT='%B%m%~%b$(git_super_status) %# '
zstyle ':completion:*' '' matcher-list 'm:{a-z}={A-Z}'

hx() {
    var="NR=="
    $(awk $var$1 ~/.histfile)
}

PATH=$PATH:/usr/local/sbin
alias ipy="python -c 'import IPython; IPython.terminal.ipapp.launch_new_instance()'"
