# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=20000
SAVEHIST=20000
bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
# zstyle :compinstall filename '/Users/ankitmittal/.zshrc'

# autoload -Uz compinit
# compinit
# End of lines added by compinstall


#copying for autojump utility

#setting up aliases
source $HOME/repos/personal/scripts/zsh/alias
source $HOME/repos/personal/scripts/zsh/func
zstyle ':completion:*' '' matcher-list 'm:{a-z}={A-Z}'

hx() {
    var="NR=="
    $(awk $var$1 ~/.histfile)
}

alias ipy="python -c 'import IPython; IPython.terminal.ipapp.launch_new_instance()'"


export EDITOR='vim'
export ZSH_TMUX_AUTOSTAR=Ttrue
PATH=$PATH:/usr/local/sbin
PATH=$PATH:/usr/local/bin


[[ -s $(brew --prefix)/etc/profile.d/autojump.sh ]] && . $(brew --prefix)/etc/profile.d/autojump.sh
plugins=(git osx tmux python history z)

